### ISSUE TITLE
Is SSR supported?

### ISSUE THREAD

**Issue by romandrahan** [crossjs/vuex-localstorage#10]
Can you add SSR support. Cause now i get reference error: `localStorage is not defined` while doing server-side rendering.

**Comment by gserrg** [comment]
You can use dom-storage for the repository. https://github.com/node-browser-compat/dom-storage
```javascript
import { Store } from 'vuex'
import createPersist from 'vuex-localstorage'
import Storage from 'dom-storage';

new Store({
  plugins: [createPersist({
    namespace: ' ',
    initialState: {},
    provider: new Storage('./db.json', { strict: false, ws: ' ' }),
    expires: 7 * 24 * 60 * 60 * 1e3
  })]
}
```

**Comment by wosevision** [comment]
@romandragan To further clarify @gserrg's proposed solution (which is the correct way I'd say), localStorage is a browser technology – its implementation exists as a property on the `window` object, which isn't present in server environments. In Node, `localStorage is not defined` means exactly what it says and that probably won't change.

In theory, that library (dom-storage) could be any other that supports the same API (`getItem()`, `setItem()`, etc) or even one you've written/adapted to use that – for instance, you could save to Node's session storage or to a database.

**Comment by gserrg** [comment]
It is worth noting that `./db.json` must be unique for each session

**Comment by vvenv** [comment]
@gserrg's solution is the correct way.

see: https://github.com/crossjs/vuex-localstorage/blob/master/test/unit/specs/storage.spec.js#L93-L100
