### ISSUE TITLE
微信安卓里面的Object.assign没有实现。

### ISSUE THREAD

**Issue by ritayzy** [crossjs/vuex-localstorage#6]
微信那么高大上产品，内置浏览器没有实现[Object.assign](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)方法，简直就是个坑，微信的真机开发，你懂的，太难调了，这里mark~一下，下面来的人不要继续入坑了，

作者能不能加个[Object.assign](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)的`polyfill实现啊 @李文富

**Comment by crossjs** [comment]
谢谢提醒。
基于按需加载的原则，我这边推荐的用法是手动引入 polyfill，参见：

webpack + core-js
https://github.com/crossjs/plato/blob/dev/src/polyfills/index.js#L4
https://github.com/crossjs/plato/blob/dev/webpack.config.babel.js#L48

**Comment by ritayzy** [comment]
嗯，谢谢啊，手动引用了。

**Comment by transtone** [comment]
链接打不开了，可否将方法写在这里？

**Comment by crossjs** [comment]
@transtone 已更新链接
