### ISSUE TITLE
Why is this called vuex-localstorage

### ISSUE THREAD

**Issue by l0rn** [crossjs/vuex-localstorage#7]
Am i missing something? There is no vuex specific logic implemented here... as far as im concerned you just wrap localstorage with serialize functions.... but then you have to just get and set the values in your vuex getters / mutations on your own, like with any othe localStorage lib

**Comment by l0rn** [comment]
See https://github.com/robinvdvleuten/vuex-persistedstate

**Comment by crossjs** [comment]
@l0rn
yes, it's nothing about Vuex.
`Vuex-PersistedState` is the right way.
Sorry for confusing you.
