### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by transtone** [crossjs/vuex-localstorage#8]
您好，更新到1.0之后，发现已经成为vuex的一个插件了。如何用在 modules 里？
```js
export default new Vuex.Store({
  plugins: [createPersist({
    namespace: 'login',
    initialState: {
      token: null   // 后台的认证jwt
    },
    // ONE_WEEK
    expires: 7 * 24 * 60 * 60 * 1e3
  })],
  modules: {
    login
  }
});
```
请问上面的`token`如何在login modules里通过mutations修改？

**Comment by crossjs** [comment]
initialState 会被 merge 到 store.state，
如果你的 login module 是 namespaced 的，
我猜想 initialState 该这么写：
```
initialState: {
  login: {
    token: null   // 后台的认证jwt
  }
 }
```

没有代码不好确定。

如果还有问题，可以继续使用 0.5.x

**Comment by transtone** [comment]
还是不行，我用回 0.5.x了。

**Comment by crossjs** [comment]
OK

1.0在参数结构上做了些调整，
以前是三个参数，现在是一个。

**Comment by transtone** [comment]
1.0 变成全局的了，只要是vuex里的数据统统保存到 localstorage，如何只保存某一些数据到 localstorage，其他的一些动态获取？

**Comment by vvenv** [comment]
https://github.com/crossjs/vuex-localstorage/blob/master/src/index.js#L97-L98
